RadioData: !Data
  stream_id: !StreamID
  class_id: !ClassID
    oui: 00-00-00
    packet_code: 0
  timestamp: !Timestamp
    integer: utc
    fractional: picoseconds
  trailer: !Trailer
    sample_frame: required

RadioContext: !Context
  stream_id: !StreamID
  timestamp: !Timestamp
    integer: utc
    fractional: picoseconds
  cif_0: !CIF0
    bandwidth: required
    rf_ref_frequency: required
    gain: required
    sample_rate: required

RadioControl: !Control
  timestamp: !Timestamp
    integer: utc
    fractional: picoseconds
  cam: !ControlAcknowledgeMode
    action_mode: execute
    permit_errors: true
    req_x: optional
    req_s: optional
    req_er: true
  controllee_id: word
  controller_id: word
  cif_0: !CIF0
    bandwidth: optional
    rf_ref_frequency: optional
    gain: optional
    sample_rate: optional
  cif_1: !CIF1
    discrete_io_32: !DiscreteIO32
      stream_enable: enable_indicator

RadioAck: !Ack
  responds_to: RadioControl

RadioQuery: !Control
  timestamp: !Timestamp
    integer: utc
    fractional: picoseconds
  cam: !ControlAcknowledgeMode
    req_s: true
    action_mode: none
  controllee_id: word
  controller_id: word
  cif_0: !CIF0
    bandwidth: optional
    rf_ref_frequency: optional
    gain: optional
    sample_rate: optional
  cif_1: !CIF1
    discrete_io_32: !DiscreteIO32
      stream_enable: enable_indicator

RadioQueryAck: !Ack
  responds_to: RadioQuery
