include(FetchContent)
set(CMAKE_POLICY_VERSION_MINIMUM 3.5)
set(ENABLE_PYTHON OFF CACHE BOOL "" FORCE)
set(ENABLE_PYTHON3 OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_APPS OFF CACHE BOOL "" FORCE)
set(ENABLE_DOCS OFF CACHE BOOL "" FORCE)
FetchContent_Declare(soapysdr
  URL https://codeload.github.com/pothosware/SoapySDR/tar.gz/1cf5a539a21414ff509ff7d0eedfc5fa8edb90c6
  URL_HASH SHA256=e680e9a6f741764b9c31b0520e577d91ad4197968d50c78db601c8a59e9ba72a
  DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_MakeAvailable(soapysdr)
FetchContent_Declare(vrtgen
  URL https://codeload.github.com/Geontech/vrtgen/tar.gz/5e7497d24069c140be431d8468655f67d25f382d
  URL_HASH SHA256=63510b707788716e330ccdfbed1c0bde079122388c1785fac66b1aef11bfe752
  DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
FetchContent_GetProperties(vrtgen)
if(NOT vrtgen_POPULATED)
  FetchContent_Populate(vrtgen)
endif()
set(GRAPHX_VRTPKTGEN "" CACHE FILEPATH "Pinned vrtpktgen executable")
get_filename_component(vrtgen_bin "${GRAPHX_VRTPKTGEN}" DIRECTORY)
if(NOT EXISTS "${GRAPHX_VRTPKTGEN}")
  message(FATAL_ERROR "GRAPHX_BUILD_VITA_RADIO requires GRAPHX_VRTPKTGEN; see radio-design.md")
endif()
set(vita_generated "${CMAKE_CURRENT_BINARY_DIR}/generated/vita")
set(vita_sources)
foreach(packet radio_data radio_context radio_control radio_ack radio_query radio_query_ack)
  list(APPEND vita_sources "${vita_generated}/${packet}.cpp")
endforeach()
add_custom_command(OUTPUT ${vita_sources}
  COMMAND "${vrtgen_bin}/python" "${CMAKE_CURRENT_SOURCE_DIR}/scripts/vita/generate.py"
    "${vita_generated}" "${CMAKE_CURRENT_SOURCE_DIR}/config/vita/radio.yaml" "${vrtgen_SOURCE_DIR}"
  DEPENDS config/vita/radio.yaml scripts/vita/generate.py VERBATIM)
add_library(graphx-vita-codec STATIC ${vita_sources})
target_include_directories(graphx-vita-codec SYSTEM PUBLIC "${vrtgen_SOURCE_DIR}/include" "${vita_generated}")
add_library(graphx-vita-radio STATIC src/vita/virtual_device.cpp src/vita/radio.cpp)
target_include_directories(graphx-vita-radio PUBLIC include)
target_link_libraries(graphx-vita-radio PUBLIC SoapySDR graphx-vita-codec graphx)
graphx_enable_analysis(graphx-vita-radio)
graphx_enable_sanitizers(graphx-vita-radio)
if(APPLE)
  target_include_directories(graphx-vita-codec SYSTEM PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src/vita/compat")
endif()

add_executable(graphx-vita-radio-app apps/vita-radio/main.cpp)
set_target_properties(graphx-vita-radio-app PROPERTIES OUTPUT_NAME graphx-vita-radio)
target_link_libraries(graphx-vita-radio-app PRIVATE graphx-vita-radio)
graphx_enable_analysis(graphx-vita-radio-app)
graphx_enable_sanitizers(graphx-vita-radio-app)
if(GRAPHX_BUILD_TESTS)
  add_executable(graphx-vita-device-test tests/test_vita_device.cpp)
  target_link_libraries(graphx-vita-device-test PRIVATE graphx-vita-radio)
  graphx_enable_analysis(graphx-vita-device-test)
  graphx_enable_sanitizers(graphx-vita-device-test)
  add_test(NAME graphx-vita-device COMMAND graphx-vita-device-test)
  add_test(NAME graphx-vita-standalone COMMAND ${Python3_EXECUTABLE}
    ${CMAKE_SOURCE_DIR}/tests/test_vita_radio.py ${CMAKE_BINARY_DIR})
  set_tests_properties(graphx-vita-standalone PROPERTIES TIMEOUT 60)
endif()
configure_file(config/vita/dependencies.json generated/vita-dependencies.json COPYONLY)
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated/vita-licenses")
configure_file("${soapysdr_SOURCE_DIR}/LICENSE_1_0.txt" generated/vita-licenses/SoapySDR.txt COPYONLY)
configure_file("${vrtgen_SOURCE_DIR}/LICENSE" generated/vita-licenses/vrtgen.txt COPYONLY)
